version: "2"
services:
  stats:
    image: dock-dock-go:local
    environment:
      DOCKER_VERSION: 1.39
      LOG_LEVEL: warn
      OUTPUT_TYPE: statsd
      OUTPUT_INTERVAL: 2000
      STATSD_SERVER_URI: http://server
      STATSD_SERVER_PORT: 8125
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    image: hopsoft/graphite-statsd
    ports:
      - 81:81 
      - 8125:8125/udp 
    volumes:
      - server-logs:/var/log
    restart: always
  
volumes:
  server-logs: