version: "2"
services:
  stats:
    image: dock-dock-go:local
    environment:
      DOCKER_VERSION: 1.39
      LOG_LEVEL: warn
      OUTPUT_TYPE: stdout
      OUTPUT_INTERVAL: 2000
      STATSD_SERVER_URI: http://localhost
      STATSD_SERVER_PORT: 8125
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    image: hopsoft/graphite-statsd
    ports:
      - 80:80 
      - 81:81 
      - 2003-2004:2003-2004 
      - 2023-2024:2023-2024 
      - 8125:8125/udp 
      - 8126:8126
    volumes:
      - server-logs:/var/log
    restart: always
  
volumes:
  server-logs: